services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - thoughtgrove-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - thoughtgrove-network

volumes:
  mongodb_data:

networks:
  thoughtgrove-network:
    driver: bridge 